"""
Base Strategy Module for the Algorithmic Trading Bot.

PANDAS/NUMPY CONCEPTS USED:
- Series.rolling(): Moving window calculations for technical indicators
- DataFrame.tail(): Getting recent data for decision making
- Boolean indexing: Filtering data based on conditions
- Series.iloc[]: Accessing specific positions in time series data

TRADING STRATEGY CONCEPTS:
- Signal generation: When to BUY, SELL, or HOLD
- Position sizing: How much to invest in each trade
- Risk management: Stop losses and position limits
- Backtesting: Testing strategy on historical data

Design Philosophy:
- Abstract base class (template for all strategies)
- Polymorphism (different strategies, same interface)
- Separation of signal generation and execution
- Comprehensive backtesting framework
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from turtle import position
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd

from config.config import get_config
from src import data
from src.utils.helpers import (
    calculate_max_drawdown,
    calculate_moving_average,
    calculate_profit_factor,
    calculate_returns,
    calculate_rsi,
    calculate_sharpe_ratio,
    calculate_win_rate,
    format_currency,
)

# === ABSTRACT BASE CLASS EXPLANATION ===
"""
ABC (Abstract Base Class) ensures that all strategy classes follow the same pattern.

Why use ABC?
- Enforces consistent interface across all strategies
- Prevents incomplete strategy implementations
- Clear contract for what each strategy must provide
- Professional software development practice

@abstractmethod means subclasses MUST implement this method
"""


@dataclass
class Signal:
    """
    Represent trading signal generated by strategy

    Why dataclass?
    - Logging for analysis
    - Immutabke record of what the strategy decided
    - Clear structure for signal information
    """

    timestamp: datetime
    symbol: str
    action: str
    confidence: float  # 0.0 to 1.0 (indication of how confident the strategy is)
    price: float
    quantity: int
    reason: str


@dataclass
class BacktestResult:
    """
    Comprehensive results from strategy backtesting

    Financial metrics used
    total_return_pct   : Raw performance (did we make money?)
    sharpe_ratio       : Risk-adjusted return (quality?)
    max_drawdown_pct   : Worst peak-to-trough loss (safety?)
    win_rate_pct       : % of trades that were profitable
    profit_factor      : Gross profit / gross loss ratio
    avg_trade_return   : Average gain/loss per trade
    """

    strategy_name: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_portfolio_value: float
    total_return_pct: float
    sharpe_ratio: float
    max_drawdown_pct: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate_pct: float
    profit_factor: float
    avg_trade_return_pct: float
    portfolio_history: pd.Series

    def to_dict(self) -> dict:
        """
        Serialise result to dictionary.

        Why exclude portfolio_history?
        - It is a full pd.Series with hundreds of rows
        - Too large for an API response or log line
        - The summary metrics above tell the story concisely

        Used by:
        - Web API to return JSON responses
        - Logging and comparison of multiple strategies
        """
        return {
            "strategy_name": self.strategy_name,
            "start_date": str(self.start_date.date()),
            "end_date": str(self.end_date.date()),
            "initial_capital": self.initial_capital,
            "final_portfolio_value": round(self.final_portfolio_value, 2),
            "total_return_pct": round(self.total_return_pct, 2),
            "sharpe_ratio": round(self.sharpe_ratio, 3),
            "max_drawdown_pct": round(self.max_drawdown_pct, 2),
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate_pct": round(self.win_rate_pct, 1),
            "profit_factor": round(self.profit_factor, 2),
            "avg_trade_return_pct": round(self.avg_trade_return_pct, 2),
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies

    Why ABC?
    - Ensure all strategies have the required methods
    - Common functionality
    - Consistent interface for main trading bot

    Eacn concrete strategy must implement:
    - generate_signal(): Decide what to do with current data
    """

    def __init__(self, name: str, initial_capital: float = 100000):
        """
        Initialise base strategy

        Args:
        - name: Strategy name for identification

        Why store the name?
        - Identification in logs and results
        - Useful when there are multiple strategies being used
        """
        self.name = name
        self.initial_capital = initial_capital
        self.config = get_config()

        # Strategy state
        self.signals_history: List[Signal] = []
        self.is_backtesting = False

        print(f"Strategy {name} initialised with ${initial_capital:,.2f}")

    @abstractmethod
    def generate_signal(self, symbol: str, data: pd.DataFrame, current_price: float, portfolio_info: Dict) -> Signal:
        """
        Generate trading signal based on current market data

        Args:
            symbol (str): stock ticker symbol
            data (pd.DataFrame): historical price data
            current_price (float): most recent price
            portfolio_info (Dict): current portfolio state

        Returns:
            Signal object with trading decision

        Why abstract?
        - Each strategy has a different logic
        - Forces implementation in concrete classes
        - Ensures consistent interface

        PANDAS DATA STRUCTURE:
        data DataFrame structure:
                        Open    High    Low     Close   Volume
        Date
        2024-01-01     100.0   102.0   99.0    101.0   1000000
        2024-01-02     101.0   103.0   100.0   102.0   1200000

        This method is the brain of each strategy
        """
        pass

    def should_buy(self, symbol: str, data: pd.DataFrame, portfolio_info: Dict) -> Tuple[bool, str]:
        """
        Determine if we should buy a stock

        Returns:
            Tuple[bool,str]: bool represents whether should buy, reason is the string

        Why separate method?
        - Can be overridden by specific strategies
        - Clear separation of concerns
        - Reusable logic across strategies
        """

        signal = self.generate_signal(symbol, data, float(data["Close"].iloc[-1]), portfolio_info)
        return (signal.action == "BUY", signal.reason)

    def should_sell(self, symbol: str, data: pd.DataFrame, portfolio_info: Dict) -> Tuple[bool, str]:
        """
        Determine if we should sell a stock
        """
        # Check if we even own this stock
        if symbol not in portfolio_info.get("positions", {}):
            return False, f"No position in {symbol} to sell"

        signal = self.generate_signal(symbol, data, float(data["Close"].iloc[-1]), portfolio_info)
        return (signal.action == "SELL", signal.reason)

    def calculate_position_size(self, symbol: str, price: float, portfolio_value: float) -> int:
        """
        Calculate how many shares to buy

        Args:
            symbol (str): Stock ticker
            price (float): Current stock price
            portfolio_value (float): Total portfolio value

        Returns:
            int: Number of shares to purchase

        Risk management
        - Never invest more than max_position_size% in one stock
        - Ensure we have enough cash
        - Rounding down of shares calculated
        """
        max_posiiton_pct = self.config.MAX_POSITION_SIZE
        target_investment = portfolio_value * max_posiiton_pct

        shares = int(target_investment / price)

        return max(0, shares)

    def add_signal(self, signal: Signal) -> None:
        """
        Record a signal for analysis

        Why track signals?
        - Strategy performance analysis
        - Historical decision audit trail
        """
        self.signals_history.append(signal)

    def backtest(
        self, data: Dict[str, pd.DataFrame], start_date: Optional[datetime] = None, end_date: Optional[datetime] = None
    ) -> BacktestResult:
        """
        Backtest strategy on historical data

        Args:
            data: Dictionary of symbol -> Dataframe
            start_date: Start date for backtest
            end_date: End date for backtest

        Backtest Process:
        1. Simulate portfolio starting with initial capital
        2. Go through each day chronologically
        3. Generate signals using only past data (no lookahead bias)
        4. Execute trades and track portfolio value
        5. Calculate performance metrics

        Why chronological simulation?
        - Realistic: mirrors real trading
        - No lookahead bias: cannot use future information
        """

        self.is_backtesting = True
        print(f"/n Starting backtest for {self.name}")

        # Setup backtest parameters
        if not data:
            raise ValueError("No data avaliable for backtesting")

        # Get data range from data
        all_dates = set()  # Prevent duplicates
        for df in data.values():
            all_dates.update(df.index)  # Grab list of date since we set timestamp as index earlier

        all_dates = sorted(all_dates)

        # Handle timezone consistency
        # yfinance returns timezone-aware dates, so let's make everything consistent
        if all_dates:
            # Check if data has timezone info
            if all_dates[0].tzinfo is not None:
                # Make comparison dates timezone-aware
                if start_date and start_date.tzinfo is None:
                    start_date = start_date.replace(tzinfo=all_dates[0].tzinfo)
                if end_date and end_date.tzinfo is None:
                    end_date = end_date.replace(tzinfo=all_dates[0].tzinfo)
        else:
            # Make comparison dates timezone-naive
            if start_date and start_date.tzinfo is not None:
                start_date = start_date.replace(tzinfo=None)
            if end_date and end_date.tzinfo is not None:
                end_date = end_date.replace(tzinfo=None)

        # Filter by date range
        if start_date:
            all_dates = [d for d in all_dates if d >= start_date]
        if end_date:
            all_dates = [d for d in all_dates if d <= end_date]

        if not all_dates:
            raise ValueError("No valid dates for backtesting")

        # .date is to just show the date instead of the time as well
        print(f"Backtesting from {all_dates[0].date} to {all_dates[-1].date()}")
        print(f"Symbols: {list(data.keys())}")

        # Initialise backtest portfolio
        cash = self.initial_capital
        positions = {}  # symbol -> quantity
        portfolio_history = {}  # date -> portfolio value
        trades = []
        buy_prices = {}  # {symbol:average_buy_price} for PnL calc

        # MAIN BACKTESTING LOOP
        for i, current_date in enumerate(all_dates):
            # current_date is the variable holding the actual date, I is the index, enumerate pairs index and the value
            daily_portfolio_value = cash
            current_prices = {}

            # Calculate current portfolio value
            for symbol in positions:
                if symbol in data and current_date in data[symbol].index:
                    # Because in main backtest loop, the index is paired with the value, which is the actual date
                    price = data[symbol].loc[current_date, "Close"]
                    current_prices[symbol] = price
                    daily_portfolio_value += price * positions[symbol]

            portfolio_history[current_date] = daily_portfolio_value

            # Generate signals for each symbol
            for symbol, symbol_data in data.items():
                historical_data = symbol_data[symbol_data.index <= current_date]

                if len(historical_data) < 20:
                    continue

                if current_date not in symbol_data.index:
                    continue

                current_price = float(symbol_data.loc[current_date, "Close"])

                # Portfolio info for strategy
                portfolio_info = {
                    "cash": cash,
                    "total_value": daily_portfolio_value,
                    "positions": positions.copy(),
                    "current_prices": current_prices,
                }

                # Generate signal using only past data
                signal = self.generate_signal(symbol, historical_data, current_price, portfolio_info)

                # Execute trades based on the signal
                if signal.action == "BUY" and signal.quantity > 0:
                    cost = signal.quantity * signal.price + self.config.TRANSACTION_COST

                    if cash >= cost:
                        cash -= cost
                        positions[symbol] = positions.get(symbol, 0) + signal.quantity

                        # Track average buy price for PnL calculations
                        # Weighted average if adding to existing position
                        existing_qty = positions.get(symbol, 0) - signal.quantity
                        existing_price = buy_prices.get(symbol, 0)
                        new_qty = existing_qty + signal.quantity

                        if new_qty > 0:
                            buy_prices[symbol] = ((existing_price * existing_qty) + (new_qty * signal.price)) / new_qty

                    trades.append(
                        {
                            "date": current_date,
                            "symbol": symbol,
                            "action": "BUY",
                            "quantity": signal.quantity,
                            "price": signal.price,
                            "cost": cost,
                        }
                    )

                    if not self.is_backtesting:
                        print(f"BUY: {signal.quantity} @ ${signal.price:.2f}")

                elif signal.action == "SELL" and symbol in positions:
                    shares_to_sell = min(signal.quantity, positions[symbol])

                    if shares_to_sell > 0:
                        proceeds = shares_to_sell * signal.price - self.config.TRANSACTION_COST
                        cash += proceeds
                        positions[symbol] -= shares_to_sell

                        buy_price = buy_prices.get(symbol, signal.price)
                        trade_pnl = (signal.price - buy_price) * shares_to_sell

                        if positions[symbol] == 0:
                            del positions[symbol]
                            if symbol in buy_prices:
                                del buy_prices[symbol]

                        trades.append(
                            {
                                "date": current_date,
                                "symbol": symbol,
                                "action": "SELL",
                                "quantity": shares_to_sell,
                                "price": signal.price,
                                "proceeds": proceeds,
                                "pnl": trade_pnl,
                            }
                        )

                        if not self.is_backtesting:
                            print(f"SELL: {shares_to_sell} @ ${signal.price:.2f}")

            self.is_backtesting = False

            # Calculate performance metrics
            if not portfolio_history:
                print("⚠️  No portfolio history generated - no trades executed")
                return BacktestResult(
                    strategy_name=self.name,
                    start_date=all_dates[0],
                    end_date=all_dates[-1],
                    initial_capital=self.initial_capital,
                    final_portfolio_value=self.initial_capital,
                    total_return_pct=0.0,
                    sharpe_ratio=0.0,
                    max_drawdown_pct=0.0,
                    total_trades=0,
                    winning_trades=0,
                    losing_trades=0,
                    win_rate_pct=0.0,
                    avg_trade_return_pct=0.0,
                    portfolio_history=pd.Series([self.initial_capital]),
                )

            portfolio_series = pd.Series(portfolio_history)

            if len(portfolio_series) == 0:
                final_value = self.initial_capital
            else:
                final_value = float(portfolio_series.iloc[-1])

            total_return_pct = ((final_value - self.initial_capital) / self.initial_capital) * 100

            # Extract only SELL trades for PnL analysis
            sell_pnls = [t["pnl"] for t in trades if t["action"] == "SELL" and "pnl" in t]

            # Use helpers.py functions
            win_rate_decimal = calculate_win_rate(sell_pnls)
            profit_factor = calculate_profit_factor(sell_pnls)

            winning = sum(1 for pnl in sell_pnls if pnl > 0)
            losing = sum(1 for pnl in sell_pnls if pnl <= 0)

            avg_trade_return_pct = float(np.mean(sell_pnls)) if sell_pnls else 0

            # Calculate sharpe ratio and max drawdown
            returns = portfolio_series.pct_change().dropna()
            sharpe = calculate_sharpe_ratio(returns) if len(returns) > 1 else 0.0
            max_dd = abs(calculate_max_drawdown(portfolio_series)) * 100

            result = BacktestResult(
                strategy_name=self.name,
                start_date=all_dates[0],
                end_date=all_dates[-1],
                initial_capital=self.initial_capital,
                final_portfolio_value=final_value,
                total_return_pct=total_return_pct,
                sharpe_ratio=sharpe,
                max_drawdown_pct=max_dd,
                total_trades=len(trades),
                winning_trades=winning,
                losing_trades=losing,
                win_rate_pct=win_rate_decimal * 100,
                profit_factor=profit_factor,
                avg_trade_return_pct=avg_trade_return_pct,
                portfolio_history=portfolio_series,
            )

        self._print_backtest_results(result)
        return result

    def _print_backtest_results(self, result: BacktestResult) -> None:
        """Print formatted backtest results."""
        print(f"\n{'='*60}")
        print(f"🎯 BACKTEST RESULTS: {result.strategy_name}")
        print(f"{'='*60}")
        print(f"📅 Period: {result.start_date.date()} to {result.end_date.date()}")
        print(f"💷 Initial Capital: £{result.initial_capital:,.2f}")
        print(f"💷 Final Value: £{result.final_portfolio_value:,.2f}")
        print(f"📈 Total Return: {result.total_return_pct:+.2f}%")
        print(f"📊 Sharpe Ratio: {result.sharpe_ratio:.3f}")
        print(f"📉 Max Drawdown: {result.max_drawdown_pct:.2f}%")
        print(f"🔄 Total Trades: {result.total_trades}")
        print(f"✅ Winning Trades: {result.winning_trades}")
        print(f"❌ Losing Trades: {result.losing_trades}")
        print(f"🎯 Win Rate: {result.win_rate_pct:.1f}%")
        print(f"📊 Avg Trade Return: {result.avg_trade_return_pct:+.2f}%")
        print(f"{'='*60}")


# === EXAMPLE: SIMPLE MOVING AVERAGE CROSSOVER STRATEGY ===


class MovingAverageCrossoverStrategy(BaseStrategy):
    """
    Moving average crossover strategy

    Strategy Logic
    - BUY when short-term MA crosses above long-term MA (golden cross)
    - SELL when short-term MA crosses below long-term MA (death cross)
    - HOLD when there is no clear signal

    Why moving averages?
    - Simple and widely used
    - Godd for trending markets
    - Easy to understand and implement
    """

    def __init__(self, short_window: int = 20, long_window: int = 50, initial_capital=100000):
        """
        Initialise moving average strategy

        Args:
            short_window: Days for short-term moving average
            long_window : Days for long-term moving average

        Why these defaults?
        - 20/50 day combination is classic
        - Short enough to catch trends
        - Long enough to filter noise
        """
        if short_window > long_window:
            raise ValueError("Short window must be less than the long window")

        super().__init__(f"MA_Crossover_{short_window}_{long_window}", initial_capital)
        self.short_window = short_window
        self.long_window = long_window

    def generate_signal(self, symbol: str, data: pd.DataFrame, current_price: float, portfolio_info: Dict) -> Signal:
        """
        Generate signal based on moving average crossover

        PANDA OPERATIONS
        - Calculate moving averages using .rolling()
        - Use .iloc[-1] to obtain most recent values
        - Compare current vs previous to detect crossovers
        """

        # Need enough data for long moving average
        if len(data) < self.long_window + 1:
            return Signal(
                timestamp=datetime.now(),
                symbol=symbol,
                action="HOLD",
                confidence=0.0,
                price=current_price,
                quantity=0,
                reason=f"Insufficient data: {len(data)} < {self.long_window + 1}",
            )

        # Calculate the moving averages
        prices = data["Close"]
        short_ma = calculate_moving_average(prices, self.short_window)
        long_ma = calculate_moving_average(prices, self.long_window)

        # Get current and previous MA values
        # iloc[-1] for most recent, iloc[-2] for previous
        short_current = short_ma.iloc[-1]
        short_previous = short_ma.iloc[-2]
        long_current = long_ma.iloc[-1]
        long_previous = long_ma.iloc[-2]

        # Debug output (added for testing)
        if not self.is_backtesting:
            print(f"    {symbol} MA Debug: Short={short_current:.2f}, Long={long_current:.2f}")

        # Detect the crossover
        # Golden Cross : Short term MA crosses Long term MA
        golden_cross = short_current > long_current and short_previous <= long_previous

        # Death Cross
        death_cross = short_previous >= long_previous and short_current < long_current

        # Generate appropriate signal
        if golden_cross:
            # BUY Signal
            position_size = self.calculate_position_size(symbol, current_price, portfolio_info["total_value"])

            if not self.is_backtesting:
                print(f"    🟢 {symbol} GOLDEN CROSS detected!")

            return Signal(
                timestamp=datetime.now(),
                symbol=symbol,
                action="BUY",
                confidence=0.8,  # High confidence for clear crossover
                price=current_price,
                quantity=position_size,
                reason=f"Golden cross: {self.short_window}MA > {self.long_window}MA",
            )
        elif death_cross:
            # SELL SIGNAL
            positions_dict = portfolio_info.get("positions", {})
            current_position = positions_dict.get(symbol, "0")

            if not self.is_backtesting:
                print(f"   🔴  {symbol} DEATH CROSS detected!")

            return Signal(
                timestamp=datetime.now(),
                symbol=symbol,
                action="SELL",
                confidence=0.8,
                price=current_price,
                quantity=current_position,
                reason=f"Death cross: {self.short_window}MA < {self.long_window}MA",
            )

        else:
            # HOLD - no clear signal
            return Signal(
                timestamp=datetime.now(),
                symbol=symbol,
                action="HOLD",
                confidence=0.5,
                price=current_price,
                quantity=0,
                reason=f"No crossover signal detected",
            )
